<template>
  <div class="loadingio-spinner-double-ring-44afqiq1222">
    <div class="ldio-mk526ppnu7m">
      <div></div>
      <div></div>
      <div><div></div></div>
      <div><div></div></div>
    </div>
  </div>
</template>

<style scoped>
@keyframes ldio-mk526ppnu7m {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-mk526ppnu7m div {
  box-sizing: border-box !important;
}
.ldio-mk526ppnu7m > div {
  position: absolute;
  width: 69px;
  height: 69px;
  top: 15.5px;
  left: 15.5px;
  border-radius: 50%;
  border: 5px solid #000;
  border-color: #409eff transparent #409eff transparent;
  animation: ldio-mk526ppnu7m 1s linear infinite;
}

.ldio-mk526ppnu7m > div:nth-child(2),
.ldio-mk526ppnu7m > div:nth-child(4) {
  width: 57px;
  height: 57px;
  top: 21.5px;
  left: 21.5px;
  animation: ldio-mk526ppnu7m 1s linear infinite reverse;
}
.ldio-mk526ppnu7m > div:nth-child(2) {
  border-color: transparent #bbcedd transparent #bbcedd;
}
.ldio-mk526ppnu7m > div:nth-child(3) {
  border-color: transparent;
}
.ldio-mk526ppnu7m > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-mk526ppnu7m > div:nth-child(3) div:before,
.ldio-mk526ppnu7m > div:nth-child(3) div:after {
  content: '';
  display: block;
  position: absolute;
  width: 5px;
  height: 5px;
  top: -5px;
  left: 27px;
  background: #409eff;
  border-radius: 50%;
  box-shadow: 0 64px 0 0 #409eff;
}
.ldio-mk526ppnu7m > div:nth-child(3) div:after {
  left: -5px;
  top: 27px;
  box-shadow: 64px 0 0 0 #409eff;
}

.ldio-mk526ppnu7m > div:nth-child(4) {
  border-color: transparent;
}
.ldio-mk526ppnu7m > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-mk526ppnu7m > div:nth-child(4) div:before,
.ldio-mk526ppnu7m > div:nth-child(4) div:after {
  content: '';
  display: block;
  position: absolute;
  width: 5px;
  height: 5px;
  top: -5px;
  left: 21px;
  background: #bbcedd;
  border-radius: 50%;
  box-shadow: 0 52px 0 0 #bbcedd;
}
.ldio-mk526ppnu7m > div:nth-child(4) div:after {
  left: -5px;
  top: 21px;
  box-shadow: 52px 0 0 0 #bbcedd;
}
.loadingio-spinner-double-ring-44afqiq1222 {
  width: 64px;
  height: 64px;
  display: inline-block;
  overflow: hidden;
}
.ldio-mk526ppnu7m {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.64);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-mk526ppnu7m div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
